name: check

on:
    push:
        branches:
            - master
    pull_request:
    merge_group:

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        strategy:
            matrix:
                version: [ 1, 2 ]
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: corretto
                  java-version: 17

            - name: Check
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: "check --continue -Pkotlin.incremental=false --no-daemon"

    check-finish:
        needs: [ check ]
        runs-on: ubuntu-latest
        steps:
            - name: Finish check
              run: echo "Check finished successfully!"