name: make changes

on:
  workflow_dispatch:

jobs:
  make-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up git user
        run: |
          git config --local user.email "intellij.rust@gmail.com"
          git config --local user.name "intellij-rust-bot"

      - name: Make changes
        run: |
          echo -en "\n" >> src/main/kotlin/Main.kt
          git add src/main/kotlin/Main.kt
          git commit -m "Add empty line"
          git push origin master
